### ISSUE TITLE
[EPIC] GPF staging automation

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#385]
- [x] switch to using mambaforge for `iossifovlab-containers`
- [x] `iossifovlab-gpf-container` Docker images are huge
- [x] 	GPF conda package should work on Mac
- [x] deployment automation to `dory`
- [x] switch to Python 3.10 again

**Comment by lchorbadjiev** [comment]
First iteration on staging done.
