### ISSUE TITLE
[EPIC] GPF staging automation on dory.seqpipe.org

### ISSUE THREAD

**Issue by lchorbadjiev** [iossifovlab/gpf#398]
**Is your feature request related to a problem? Please describe.**
We want a staging environment for GPF using the internal Impala cluster.

We already have a staging build (https://nemo.seqpipe.org/job/iossifovlab/job/gpf-staging/job/master/) that, at its final stage, deploys on `dory` at `http://dory.seqpipe.org:8000`.

We have following issues with this build that should be addressed:

- [x] GPF frontpage deployed on `dory` does not work
- [x] We lack emailing configuration for the dory's staging environment - we need to add one.
- [x] Use MailHog for integration testing of user creation/management in `gpf/wdae`
- [x] Review and reorganize `settings.py` and `default_settings.py`
- [x] We don't have a Sentry GPF logging configured for dory's staging environment.
- [x] We don't have a Sentry gpfjs logging configured for dory's staging environment.
